Import('env')

env.InstallHTML(['img/output.png','img/pdf.gif','img/file-icon.png','img/eqn_cc.png','img/eqn_sum.png','img/eqn_vox.png','img/EMDBsml.gif','img/BioInfo3Dsmall.png'],'img')
env.InstallHTML(['file/1oel_subunit.pdb','file/emd_1080_one_ring.mrc', 'file/1z5s_15.mrc', 'file/1z5s_A.pdb', 'file/1z5s_B.pdb', 'file/1z5s_C.pdb', 'file/1z5s_D.pdb'],'file')
env.InstallHTML(['js/tab.js','js/tab.css'],'js')
